/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ResetarSenhaRouteImport } from './routes/resetar-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroIndexRouteImport } from './routes/cadastro.index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin.login'
import { Route as CadastroSucessoRouteImport } from './routes/cadastro.sucesso'
import { Route as CadastroSlugRouteImport } from './routes/cadastro.$slug'
import { Route as CadastroMembroSlugRouteImport } from './routes/cadastro-membro.$slug'
import { Route as AuthUsuariosRouteImport } from './routes/_auth.usuarios'
import { Route as AuthRelatoriosRouteImport } from './routes/_auth.relatorios'
import { Route as AuthQrCadastroRouteImport } from './routes/_auth.qr-cadastro'
import { Route as AuthModulosRouteImport } from './routes/_auth.modulos'
import { Route as AuthMinisteriosRouteImport } from './routes/_auth.ministerios'
import { Route as AuthMigracaoRouteImport } from './routes/_auth.migracao'
import { Route as AuthMembrosMetricasRouteImport } from './routes/_auth.membros-metricas'
import { Route as AuthManualRouteImport } from './routes/_auth.manual'
import { Route as AuthIgrejasRouteImport } from './routes/_auth.igrejas'
import { Route as AuthFollowupWhatsappRouteImport } from './routes/_auth.followup-whatsapp'
import { Route as AuthDiscipuladoresRouteImport } from './routes/_auth.discipuladores'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as SlugLoginRouteImport } from './routes/$slug.login'
import { Route as AuthMembrosIndexRouteImport } from './routes/_auth.membros.index'
import { Route as AuthDiscipuladoIndexRouteImport } from './routes/_auth.discipulado.index'
import { Route as AuthConvertidosIndexRouteImport } from './routes/_auth.convertidos.index'
import { Route as AuthMembrosNovoRouteImport } from './routes/_auth.membros.novo'
import { Route as AuthDiscipuladoIdRouteImport } from './routes/_auth.discipulado.$id'
import { Route as AuthConvertidosNovoRouteImport } from './routes/_auth.convertidos.novo'
import { Route as AuthMembrosIdIndexRouteImport } from './routes/_auth.membros.$id.index'
import { Route as AuthConvertidosIdIndexRouteImport } from './routes/_auth.convertidos.$id.index'
import { Route as AuthMembrosIdEditarRouteImport } from './routes/_auth.membros.$id.editar'
import { Route as AuthConvertidosIdJornadaRouteImport } from './routes/_auth.convertidos.$id.jornada'
import { Route as AuthConvertidosIdEditarRouteImport } from './routes/_auth.convertidos.$id.editar'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetarSenhaRoute = ResetarSenhaRouteImport.update({
  id: '/resetar-senha',
  path: '/resetar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroIndexRoute = CadastroIndexRouteImport.update({
  id: '/cadastro/',
  path: '/cadastro/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/superadmin/login',
  path: '/superadmin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroSucessoRoute = CadastroSucessoRouteImport.update({
  id: '/cadastro/sucesso',
  path: '/cadastro/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroSlugRoute = CadastroSlugRouteImport.update({
  id: '/cadastro/$slug',
  path: '/cadastro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroMembroSlugRoute = CadastroMembroSlugRouteImport.update({
  id: '/cadastro-membro/$slug',
  path: '/cadastro-membro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsuariosRoute = AuthUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRelatoriosRoute = AuthRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQrCadastroRoute = AuthQrCadastroRouteImport.update({
  id: '/qr-cadastro',
  path: '/qr-cadastro',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModulosRoute = AuthModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMinisteriosRoute = AuthMinisteriosRouteImport.update({
  id: '/ministerios',
  path: '/ministerios',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMigracaoRoute = AuthMigracaoRouteImport.update({
  id: '/migracao',
  path: '/migracao',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMembrosMetricasRoute = AuthMembrosMetricasRouteImport.update({
  id: '/membros-metricas',
  path: '/membros-metricas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthManualRoute = AuthManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIgrejasRoute = AuthIgrejasRouteImport.update({
  id: '/igrejas',
  path: '/igrejas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFollowupWhatsappRoute = AuthFollowupWhatsappRouteImport.update({
  id: '/followup-whatsapp',
  path: '/followup-whatsapp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDiscipuladoresRoute = AuthDiscipuladoresRouteImport.update({
  id: '/discipuladores',
  path: '/discipuladores',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const SlugLoginRoute = SlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SlugRoute,
} as any)
const AuthMembrosIndexRoute = AuthMembrosIndexRouteImport.update({
  id: '/membros/',
  path: '/membros/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDiscipuladoIndexRoute = AuthDiscipuladoIndexRouteImport.update({
  id: '/discipulado/',
  path: '/discipulado/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConvertidosIndexRoute = AuthConvertidosIndexRouteImport.update({
  id: '/convertidos/',
  path: '/convertidos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMembrosNovoRoute = AuthMembrosNovoRouteImport.update({
  id: '/membros/novo',
  path: '/membros/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDiscipuladoIdRoute = AuthDiscipuladoIdRouteImport.update({
  id: '/discipulado/$id',
  path: '/discipulado/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConvertidosNovoRoute = AuthConvertidosNovoRouteImport.update({
  id: '/convertidos/novo',
  path: '/convertidos/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMembrosIdIndexRoute = AuthMembrosIdIndexRouteImport.update({
  id: '/membros/$id/',
  path: '/membros/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConvertidosIdIndexRoute = AuthConvertidosIdIndexRouteImport.update({
  id: '/convertidos/$id/',
  path: '/convertidos/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMembrosIdEditarRoute = AuthMembrosIdEditarRouteImport.update({
  id: '/membros/$id/editar',
  path: '/membros/$id/editar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConvertidosIdJornadaRoute =
  AuthConvertidosIdJornadaRouteImport.update({
    id: '/convertidos/$id/jornada',
    path: '/convertidos/$id/jornada',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthConvertidosIdEditarRoute = AuthConvertidosIdEditarRouteImport.update({
  id: '/convertidos/$id/editar',
  path: '/convertidos/$id/editar',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/resetar-senha': typeof ResetarSenhaRoute
  '/termos': typeof TermosRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/$slug/login': typeof SlugLoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/discipuladores': typeof AuthDiscipuladoresRoute
  '/followup-whatsapp': typeof AuthFollowupWhatsappRoute
  '/igrejas': typeof AuthIgrejasRoute
  '/manual': typeof AuthManualRoute
  '/membros-metricas': typeof AuthMembrosMetricasRoute
  '/migracao': typeof AuthMigracaoRoute
  '/ministerios': typeof AuthMinisteriosRoute
  '/modulos': typeof AuthModulosRoute
  '/qr-cadastro': typeof AuthQrCadastroRoute
  '/relatorios': typeof AuthRelatoriosRoute
  '/usuarios': typeof AuthUsuariosRoute
  '/cadastro-membro/$slug': typeof CadastroMembroSlugRoute
  '/cadastro/$slug': typeof CadastroSlugRoute
  '/cadastro/sucesso': typeof CadastroSucessoRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/$slug/': typeof SlugIndexRoute
  '/cadastro/': typeof CadastroIndexRoute
  '/convertidos/novo': typeof AuthConvertidosNovoRoute
  '/discipulado/$id': typeof AuthDiscipuladoIdRoute
  '/membros/novo': typeof AuthMembrosNovoRoute
  '/convertidos/': typeof AuthConvertidosIndexRoute
  '/discipulado/': typeof AuthDiscipuladoIndexRoute
  '/membros/': typeof AuthMembrosIndexRoute
  '/convertidos/$id/editar': typeof AuthConvertidosIdEditarRoute
  '/convertidos/$id/jornada': typeof AuthConvertidosIdJornadaRoute
  '/membros/$id/editar': typeof AuthMembrosIdEditarRoute
  '/convertidos/$id/': typeof AuthConvertidosIdIndexRoute
  '/membros/$id/': typeof AuthMembrosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/resetar-senha': typeof ResetarSenhaRoute
  '/termos': typeof TermosRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/$slug/login': typeof SlugLoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/discipuladores': typeof AuthDiscipuladoresRoute
  '/followup-whatsapp': typeof AuthFollowupWhatsappRoute
  '/igrejas': typeof AuthIgrejasRoute
  '/manual': typeof AuthManualRoute
  '/membros-metricas': typeof AuthMembrosMetricasRoute
  '/migracao': typeof AuthMigracaoRoute
  '/ministerios': typeof AuthMinisteriosRoute
  '/modulos': typeof AuthModulosRoute
  '/qr-cadastro': typeof AuthQrCadastroRoute
  '/relatorios': typeof AuthRelatoriosRoute
  '/usuarios': typeof AuthUsuariosRoute
  '/cadastro-membro/$slug': typeof CadastroMembroSlugRoute
  '/cadastro/$slug': typeof CadastroSlugRoute
  '/cadastro/sucesso': typeof CadastroSucessoRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/$slug': typeof SlugIndexRoute
  '/cadastro': typeof CadastroIndexRoute
  '/convertidos/novo': typeof AuthConvertidosNovoRoute
  '/discipulado/$id': typeof AuthDiscipuladoIdRoute
  '/membros/novo': typeof AuthMembrosNovoRoute
  '/convertidos': typeof AuthConvertidosIndexRoute
  '/discipulado': typeof AuthDiscipuladoIndexRoute
  '/membros': typeof AuthMembrosIndexRoute
  '/convertidos/$id/editar': typeof AuthConvertidosIdEditarRoute
  '/convertidos/$id/jornada': typeof AuthConvertidosIdJornadaRoute
  '/membros/$id/editar': typeof AuthMembrosIdEditarRoute
  '/convertidos/$id': typeof AuthConvertidosIdIndexRoute
  '/membros/$id': typeof AuthMembrosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/resetar-senha': typeof ResetarSenhaRoute
  '/termos': typeof TermosRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/$slug/login': typeof SlugLoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/discipuladores': typeof AuthDiscipuladoresRoute
  '/_auth/followup-whatsapp': typeof AuthFollowupWhatsappRoute
  '/_auth/igrejas': typeof AuthIgrejasRoute
  '/_auth/manual': typeof AuthManualRoute
  '/_auth/membros-metricas': typeof AuthMembrosMetricasRoute
  '/_auth/migracao': typeof AuthMigracaoRoute
  '/_auth/ministerios': typeof AuthMinisteriosRoute
  '/_auth/modulos': typeof AuthModulosRoute
  '/_auth/qr-cadastro': typeof AuthQrCadastroRoute
  '/_auth/relatorios': typeof AuthRelatoriosRoute
  '/_auth/usuarios': typeof AuthUsuariosRoute
  '/cadastro-membro/$slug': typeof CadastroMembroSlugRoute
  '/cadastro/$slug': typeof CadastroSlugRoute
  '/cadastro/sucesso': typeof CadastroSucessoRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/$slug/': typeof SlugIndexRoute
  '/cadastro/': typeof CadastroIndexRoute
  '/_auth/convertidos/novo': typeof AuthConvertidosNovoRoute
  '/_auth/discipulado/$id': typeof AuthDiscipuladoIdRoute
  '/_auth/membros/novo': typeof AuthMembrosNovoRoute
  '/_auth/convertidos/': typeof AuthConvertidosIndexRoute
  '/_auth/discipulado/': typeof AuthDiscipuladoIndexRoute
  '/_auth/membros/': typeof AuthMembrosIndexRoute
  '/_auth/convertidos/$id/editar': typeof AuthConvertidosIdEditarRoute
  '/_auth/convertidos/$id/jornada': typeof AuthConvertidosIdJornadaRoute
  '/_auth/membros/$id/editar': typeof AuthMembrosIdEditarRoute
  '/_auth/convertidos/$id/': typeof AuthConvertidosIdIndexRoute
  '/_auth/membros/$id/': typeof AuthMembrosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/esqueci-senha'
    | '/login'
    | '/resetar-senha'
    | '/termos'
    | '/trocar-senha'
    | '/$slug/login'
    | '/dashboard'
    | '/discipuladores'
    | '/followup-whatsapp'
    | '/igrejas'
    | '/manual'
    | '/membros-metricas'
    | '/migracao'
    | '/ministerios'
    | '/modulos'
    | '/qr-cadastro'
    | '/relatorios'
    | '/usuarios'
    | '/cadastro-membro/$slug'
    | '/cadastro/$slug'
    | '/cadastro/sucesso'
    | '/superadmin/login'
    | '/$slug/'
    | '/cadastro/'
    | '/convertidos/novo'
    | '/discipulado/$id'
    | '/membros/novo'
    | '/convertidos/'
    | '/discipulado/'
    | '/membros/'
    | '/convertidos/$id/editar'
    | '/convertidos/$id/jornada'
    | '/membros/$id/editar'
    | '/convertidos/$id/'
    | '/membros/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/esqueci-senha'
    | '/login'
    | '/resetar-senha'
    | '/termos'
    | '/trocar-senha'
    | '/$slug/login'
    | '/dashboard'
    | '/discipuladores'
    | '/followup-whatsapp'
    | '/igrejas'
    | '/manual'
    | '/membros-metricas'
    | '/migracao'
    | '/ministerios'
    | '/modulos'
    | '/qr-cadastro'
    | '/relatorios'
    | '/usuarios'
    | '/cadastro-membro/$slug'
    | '/cadastro/$slug'
    | '/cadastro/sucesso'
    | '/superadmin/login'
    | '/$slug'
    | '/cadastro'
    | '/convertidos/novo'
    | '/discipulado/$id'
    | '/membros/novo'
    | '/convertidos'
    | '/discipulado'
    | '/membros'
    | '/convertidos/$id/editar'
    | '/convertidos/$id/jornada'
    | '/membros/$id/editar'
    | '/convertidos/$id'
    | '/membros/$id'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_auth'
    | '/esqueci-senha'
    | '/login'
    | '/resetar-senha'
    | '/termos'
    | '/trocar-senha'
    | '/$slug/login'
    | '/_auth/dashboard'
    | '/_auth/discipuladores'
    | '/_auth/followup-whatsapp'
    | '/_auth/igrejas'
    | '/_auth/manual'
    | '/_auth/membros-metricas'
    | '/_auth/migracao'
    | '/_auth/ministerios'
    | '/_auth/modulos'
    | '/_auth/qr-cadastro'
    | '/_auth/relatorios'
    | '/_auth/usuarios'
    | '/cadastro-membro/$slug'
    | '/cadastro/$slug'
    | '/cadastro/sucesso'
    | '/superadmin/login'
    | '/$slug/'
    | '/cadastro/'
    | '/_auth/convertidos/novo'
    | '/_auth/discipulado/$id'
    | '/_auth/membros/novo'
    | '/_auth/convertidos/'
    | '/_auth/discipulado/'
    | '/_auth/membros/'
    | '/_auth/convertidos/$id/editar'
    | '/_auth/convertidos/$id/jornada'
    | '/_auth/membros/$id/editar'
    | '/_auth/convertidos/$id/'
    | '/_auth/membros/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  ResetarSenhaRoute: typeof ResetarSenhaRoute
  TermosRoute: typeof TermosRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  CadastroMembroSlugRoute: typeof CadastroMembroSlugRoute
  CadastroSlugRoute: typeof CadastroSlugRoute
  CadastroSucessoRoute: typeof CadastroSucessoRoute
  SuperadminLoginRoute: typeof SuperadminLoginRoute
  CadastroIndexRoute: typeof CadastroIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetar-senha': {
      id: '/resetar-senha'
      path: '/resetar-senha'
      fullPath: '/resetar-senha'
      preLoaderRoute: typeof ResetarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/': {
      id: '/cadastro/'
      path: '/cadastro'
      fullPath: '/cadastro/'
      preLoaderRoute: typeof CadastroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/superadmin/login': {
      id: '/superadmin/login'
      path: '/superadmin/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/sucesso': {
      id: '/cadastro/sucesso'
      path: '/cadastro/sucesso'
      fullPath: '/cadastro/sucesso'
      preLoaderRoute: typeof CadastroSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/$slug': {
      id: '/cadastro/$slug'
      path: '/cadastro/$slug'
      fullPath: '/cadastro/$slug'
      preLoaderRoute: typeof CadastroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-membro/$slug': {
      id: '/cadastro-membro/$slug'
      path: '/cadastro-membro/$slug'
      fullPath: '/cadastro-membro/$slug'
      preLoaderRoute: typeof CadastroMembroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/usuarios': {
      id: '/_auth/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthUsuariosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios': {
      id: '/_auth/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthRelatoriosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/qr-cadastro': {
      id: '/_auth/qr-cadastro'
      path: '/qr-cadastro'
      fullPath: '/qr-cadastro'
      preLoaderRoute: typeof AuthQrCadastroRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/modulos': {
      id: '/_auth/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof AuthModulosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ministerios': {
      id: '/_auth/ministerios'
      path: '/ministerios'
      fullPath: '/ministerios'
      preLoaderRoute: typeof AuthMinisteriosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/migracao': {
      id: '/_auth/migracao'
      path: '/migracao'
      fullPath: '/migracao'
      preLoaderRoute: typeof AuthMigracaoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/membros-metricas': {
      id: '/_auth/membros-metricas'
      path: '/membros-metricas'
      fullPath: '/membros-metricas'
      preLoaderRoute: typeof AuthMembrosMetricasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/manual': {
      id: '/_auth/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof AuthManualRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/igrejas': {
      id: '/_auth/igrejas'
      path: '/igrejas'
      fullPath: '/igrejas'
      preLoaderRoute: typeof AuthIgrejasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/followup-whatsapp': {
      id: '/_auth/followup-whatsapp'
      path: '/followup-whatsapp'
      fullPath: '/followup-whatsapp'
      preLoaderRoute: typeof AuthFollowupWhatsappRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/discipuladores': {
      id: '/_auth/discipuladores'
      path: '/discipuladores'
      fullPath: '/discipuladores'
      preLoaderRoute: typeof AuthDiscipuladoresRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/$slug/login': {
      id: '/$slug/login'
      path: '/login'
      fullPath: '/$slug/login'
      preLoaderRoute: typeof SlugLoginRouteImport
      parentRoute: typeof SlugRoute
    }
    '/_auth/membros/': {
      id: '/_auth/membros/'
      path: '/membros'
      fullPath: '/membros/'
      preLoaderRoute: typeof AuthMembrosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/discipulado/': {
      id: '/_auth/discipulado/'
      path: '/discipulado'
      fullPath: '/discipulado/'
      preLoaderRoute: typeof AuthDiscipuladoIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/convertidos/': {
      id: '/_auth/convertidos/'
      path: '/convertidos'
      fullPath: '/convertidos/'
      preLoaderRoute: typeof AuthConvertidosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/membros/novo': {
      id: '/_auth/membros/novo'
      path: '/membros/novo'
      fullPath: '/membros/novo'
      preLoaderRoute: typeof AuthMembrosNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/discipulado/$id': {
      id: '/_auth/discipulado/$id'
      path: '/discipulado/$id'
      fullPath: '/discipulado/$id'
      preLoaderRoute: typeof AuthDiscipuladoIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/convertidos/novo': {
      id: '/_auth/convertidos/novo'
      path: '/convertidos/novo'
      fullPath: '/convertidos/novo'
      preLoaderRoute: typeof AuthConvertidosNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/membros/$id/': {
      id: '/_auth/membros/$id/'
      path: '/membros/$id'
      fullPath: '/membros/$id/'
      preLoaderRoute: typeof AuthMembrosIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/convertidos/$id/': {
      id: '/_auth/convertidos/$id/'
      path: '/convertidos/$id'
      fullPath: '/convertidos/$id/'
      preLoaderRoute: typeof AuthConvertidosIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/membros/$id/editar': {
      id: '/_auth/membros/$id/editar'
      path: '/membros/$id/editar'
      fullPath: '/membros/$id/editar'
      preLoaderRoute: typeof AuthMembrosIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/convertidos/$id/jornada': {
      id: '/_auth/convertidos/$id/jornada'
      path: '/convertidos/$id/jornada'
      fullPath: '/convertidos/$id/jornada'
      preLoaderRoute: typeof AuthConvertidosIdJornadaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/convertidos/$id/editar': {
      id: '/_auth/convertidos/$id/editar'
      path: '/convertidos/$id/editar'
      fullPath: '/convertidos/$id/editar'
      preLoaderRoute: typeof AuthConvertidosIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface SlugRouteChildren {
  SlugLoginRoute: typeof SlugLoginRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugLoginRoute: SlugLoginRoute,
  SlugIndexRoute: SlugIndexRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDiscipuladoresRoute: typeof AuthDiscipuladoresRoute
  AuthFollowupWhatsappRoute: typeof AuthFollowupWhatsappRoute
  AuthIgrejasRoute: typeof AuthIgrejasRoute
  AuthManualRoute: typeof AuthManualRoute
  AuthMembrosMetricasRoute: typeof AuthMembrosMetricasRoute
  AuthMigracaoRoute: typeof AuthMigracaoRoute
  AuthMinisteriosRoute: typeof AuthMinisteriosRoute
  AuthModulosRoute: typeof AuthModulosRoute
  AuthQrCadastroRoute: typeof AuthQrCadastroRoute
  AuthRelatoriosRoute: typeof AuthRelatoriosRoute
  AuthUsuariosRoute: typeof AuthUsuariosRoute
  AuthConvertidosNovoRoute: typeof AuthConvertidosNovoRoute
  AuthDiscipuladoIdRoute: typeof AuthDiscipuladoIdRoute
  AuthMembrosNovoRoute: typeof AuthMembrosNovoRoute
  AuthConvertidosIndexRoute: typeof AuthConvertidosIndexRoute
  AuthDiscipuladoIndexRoute: typeof AuthDiscipuladoIndexRoute
  AuthMembrosIndexRoute: typeof AuthMembrosIndexRoute
  AuthConvertidosIdEditarRoute: typeof AuthConvertidosIdEditarRoute
  AuthConvertidosIdJornadaRoute: typeof AuthConvertidosIdJornadaRoute
  AuthMembrosIdEditarRoute: typeof AuthMembrosIdEditarRoute
  AuthConvertidosIdIndexRoute: typeof AuthConvertidosIdIndexRoute
  AuthMembrosIdIndexRoute: typeof AuthMembrosIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDiscipuladoresRoute: AuthDiscipuladoresRoute,
  AuthFollowupWhatsappRoute: AuthFollowupWhatsappRoute,
  AuthIgrejasRoute: AuthIgrejasRoute,
  AuthManualRoute: AuthManualRoute,
  AuthMembrosMetricasRoute: AuthMembrosMetricasRoute,
  AuthMigracaoRoute: AuthMigracaoRoute,
  AuthMinisteriosRoute: AuthMinisteriosRoute,
  AuthModulosRoute: AuthModulosRoute,
  AuthQrCadastroRoute: AuthQrCadastroRoute,
  AuthRelatoriosRoute: AuthRelatoriosRoute,
  AuthUsuariosRoute: AuthUsuariosRoute,
  AuthConvertidosNovoRoute: AuthConvertidosNovoRoute,
  AuthDiscipuladoIdRoute: AuthDiscipuladoIdRoute,
  AuthMembrosNovoRoute: AuthMembrosNovoRoute,
  AuthConvertidosIndexRoute: AuthConvertidosIndexRoute,
  AuthDiscipuladoIndexRoute: AuthDiscipuladoIndexRoute,
  AuthMembrosIndexRoute: AuthMembrosIndexRoute,
  AuthConvertidosIdEditarRoute: AuthConvertidosIdEditarRoute,
  AuthConvertidosIdJornadaRoute: AuthConvertidosIdJornadaRoute,
  AuthMembrosIdEditarRoute: AuthMembrosIdEditarRoute,
  AuthConvertidosIdIndexRoute: AuthConvertidosIdIndexRoute,
  AuthMembrosIdIndexRoute: AuthMembrosIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  ResetarSenhaRoute: ResetarSenhaRoute,
  TermosRoute: TermosRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  CadastroMembroSlugRoute: CadastroMembroSlugRoute,
  CadastroSlugRoute: CadastroSlugRoute,
  CadastroSucessoRoute: CadastroSucessoRoute,
  SuperadminLoginRoute: SuperadminLoginRoute,
  CadastroIndexRoute: CadastroIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
