/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as CadastroSlugRouteImport } from './routes/cadastro.$slug'
import { Route as AuthUsuariosRouteImport } from './routes/_auth.usuarios'
import { Route as AuthRelatoriosRouteImport } from './routes/_auth.relatorios'
import { Route as AuthQrCadastroRouteImport } from './routes/_auth.qr-cadastro'
import { Route as AuthModulosRouteImport } from './routes/_auth.modulos'
import { Route as AuthManualRouteImport } from './routes/_auth.manual'
import { Route as AuthIgrejasRouteImport } from './routes/_auth.igrejas'
import { Route as AuthDiscipuladoresRouteImport } from './routes/_auth.discipuladores'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as SlugLoginRouteImport } from './routes/$slug.login'
import { Route as AuthDiscipuladoIndexRouteImport } from './routes/_auth.discipulado.index'
import { Route as AuthConvertidosIndexRouteImport } from './routes/_auth.convertidos.index'
import { Route as AuthDiscipuladoIdRouteImport } from './routes/_auth.discipulado.$id'
import { Route as AuthConvertidosNovoRouteImport } from './routes/_auth.convertidos.novo'
import { Route as AuthConvertidosIdIndexRouteImport } from './routes/_auth.convertidos.$id.index'
import { Route as AuthConvertidosIdJornadaRouteImport } from './routes/_auth.convertidos.$id.jornada'
import { Route as AuthConvertidosIdEditarRouteImport } from './routes/_auth.convertidos.$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const CadastroSlugRoute = CadastroSlugRouteImport.update({
  id: '/cadastro/$slug',
  path: '/cadastro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsuariosRoute = AuthUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRelatoriosRoute = AuthRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQrCadastroRoute = AuthQrCadastroRouteImport.update({
  id: '/qr-cadastro',
  path: '/qr-cadastro',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModulosRoute = AuthModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthManualRoute = AuthManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIgrejasRoute = AuthIgrejasRouteImport.update({
  id: '/igrejas',
  path: '/igrejas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDiscipuladoresRoute = AuthDiscipuladoresRouteImport.update({
  id: '/discipuladores',
  path: '/discipuladores',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const SlugLoginRoute = SlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SlugRoute,
} as any)
const AuthDiscipuladoIndexRoute = AuthDiscipuladoIndexRouteImport.update({
  id: '/discipulado/',
  path: '/discipulado/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConvertidosIndexRoute = AuthConvertidosIndexRouteImport.update({
  id: '/convertidos/',
  path: '/convertidos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDiscipuladoIdRoute = AuthDiscipuladoIdRouteImport.update({
  id: '/discipulado/$id',
  path: '/discipulado/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConvertidosNovoRoute = AuthConvertidosNovoRouteImport.update({
  id: '/convertidos/novo',
  path: '/convertidos/novo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConvertidosIdIndexRoute = AuthConvertidosIdIndexRouteImport.update({
  id: '/convertidos/$id/',
  path: '/convertidos/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConvertidosIdJornadaRoute =
  AuthConvertidosIdJornadaRouteImport.update({
    id: '/convertidos/$id/jornada',
    path: '/convertidos/$id/jornada',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthConvertidosIdEditarRoute = AuthConvertidosIdEditarRouteImport.update({
  id: '/convertidos/$id/editar',
  path: '/convertidos/$id/editar',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/login': typeof LoginRoute
  '/$slug/login': typeof SlugLoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/discipuladores': typeof AuthDiscipuladoresRoute
  '/igrejas': typeof AuthIgrejasRoute
  '/manual': typeof AuthManualRoute
  '/modulos': typeof AuthModulosRoute
  '/qr-cadastro': typeof AuthQrCadastroRoute
  '/relatorios': typeof AuthRelatoriosRoute
  '/usuarios': typeof AuthUsuariosRoute
  '/cadastro/$slug': typeof CadastroSlugRoute
  '/$slug/': typeof SlugIndexRoute
  '/convertidos/novo': typeof AuthConvertidosNovoRoute
  '/discipulado/$id': typeof AuthDiscipuladoIdRoute
  '/convertidos/': typeof AuthConvertidosIndexRoute
  '/discipulado/': typeof AuthDiscipuladoIndexRoute
  '/convertidos/$id/editar': typeof AuthConvertidosIdEditarRoute
  '/convertidos/$id/jornada': typeof AuthConvertidosIdJornadaRoute
  '/convertidos/$id/': typeof AuthConvertidosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$slug/login': typeof SlugLoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/discipuladores': typeof AuthDiscipuladoresRoute
  '/igrejas': typeof AuthIgrejasRoute
  '/manual': typeof AuthManualRoute
  '/modulos': typeof AuthModulosRoute
  '/qr-cadastro': typeof AuthQrCadastroRoute
  '/relatorios': typeof AuthRelatoriosRoute
  '/usuarios': typeof AuthUsuariosRoute
  '/cadastro/$slug': typeof CadastroSlugRoute
  '/$slug': typeof SlugIndexRoute
  '/convertidos/novo': typeof AuthConvertidosNovoRoute
  '/discipulado/$id': typeof AuthDiscipuladoIdRoute
  '/convertidos': typeof AuthConvertidosIndexRoute
  '/discipulado': typeof AuthDiscipuladoIndexRoute
  '/convertidos/$id/editar': typeof AuthConvertidosIdEditarRoute
  '/convertidos/$id/jornada': typeof AuthConvertidosIdJornadaRoute
  '/convertidos/$id': typeof AuthConvertidosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/$slug/login': typeof SlugLoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/discipuladores': typeof AuthDiscipuladoresRoute
  '/_auth/igrejas': typeof AuthIgrejasRoute
  '/_auth/manual': typeof AuthManualRoute
  '/_auth/modulos': typeof AuthModulosRoute
  '/_auth/qr-cadastro': typeof AuthQrCadastroRoute
  '/_auth/relatorios': typeof AuthRelatoriosRoute
  '/_auth/usuarios': typeof AuthUsuariosRoute
  '/cadastro/$slug': typeof CadastroSlugRoute
  '/$slug/': typeof SlugIndexRoute
  '/_auth/convertidos/novo': typeof AuthConvertidosNovoRoute
  '/_auth/discipulado/$id': typeof AuthDiscipuladoIdRoute
  '/_auth/convertidos/': typeof AuthConvertidosIndexRoute
  '/_auth/discipulado/': typeof AuthDiscipuladoIndexRoute
  '/_auth/convertidos/$id/editar': typeof AuthConvertidosIdEditarRoute
  '/_auth/convertidos/$id/jornada': typeof AuthConvertidosIdJornadaRoute
  '/_auth/convertidos/$id/': typeof AuthConvertidosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/login'
    | '/$slug/login'
    | '/dashboard'
    | '/discipuladores'
    | '/igrejas'
    | '/manual'
    | '/modulos'
    | '/qr-cadastro'
    | '/relatorios'
    | '/usuarios'
    | '/cadastro/$slug'
    | '/$slug/'
    | '/convertidos/novo'
    | '/discipulado/$id'
    | '/convertidos/'
    | '/discipulado/'
    | '/convertidos/$id/editar'
    | '/convertidos/$id/jornada'
    | '/convertidos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$slug/login'
    | '/dashboard'
    | '/discipuladores'
    | '/igrejas'
    | '/manual'
    | '/modulos'
    | '/qr-cadastro'
    | '/relatorios'
    | '/usuarios'
    | '/cadastro/$slug'
    | '/$slug'
    | '/convertidos/novo'
    | '/discipulado/$id'
    | '/convertidos'
    | '/discipulado'
    | '/convertidos/$id/editar'
    | '/convertidos/$id/jornada'
    | '/convertidos/$id'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_auth'
    | '/login'
    | '/$slug/login'
    | '/_auth/dashboard'
    | '/_auth/discipuladores'
    | '/_auth/igrejas'
    | '/_auth/manual'
    | '/_auth/modulos'
    | '/_auth/qr-cadastro'
    | '/_auth/relatorios'
    | '/_auth/usuarios'
    | '/cadastro/$slug'
    | '/$slug/'
    | '/_auth/convertidos/novo'
    | '/_auth/discipulado/$id'
    | '/_auth/convertidos/'
    | '/_auth/discipulado/'
    | '/_auth/convertidos/$id/editar'
    | '/_auth/convertidos/$id/jornada'
    | '/_auth/convertidos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  CadastroSlugRoute: typeof CadastroSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/cadastro/$slug': {
      id: '/cadastro/$slug'
      path: '/cadastro/$slug'
      fullPath: '/cadastro/$slug'
      preLoaderRoute: typeof CadastroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/usuarios': {
      id: '/_auth/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthUsuariosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios': {
      id: '/_auth/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthRelatoriosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/qr-cadastro': {
      id: '/_auth/qr-cadastro'
      path: '/qr-cadastro'
      fullPath: '/qr-cadastro'
      preLoaderRoute: typeof AuthQrCadastroRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/modulos': {
      id: '/_auth/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof AuthModulosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/manual': {
      id: '/_auth/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof AuthManualRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/igrejas': {
      id: '/_auth/igrejas'
      path: '/igrejas'
      fullPath: '/igrejas'
      preLoaderRoute: typeof AuthIgrejasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/discipuladores': {
      id: '/_auth/discipuladores'
      path: '/discipuladores'
      fullPath: '/discipuladores'
      preLoaderRoute: typeof AuthDiscipuladoresRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/$slug/login': {
      id: '/$slug/login'
      path: '/login'
      fullPath: '/$slug/login'
      preLoaderRoute: typeof SlugLoginRouteImport
      parentRoute: typeof SlugRoute
    }
    '/_auth/discipulado/': {
      id: '/_auth/discipulado/'
      path: '/discipulado'
      fullPath: '/discipulado/'
      preLoaderRoute: typeof AuthDiscipuladoIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/convertidos/': {
      id: '/_auth/convertidos/'
      path: '/convertidos'
      fullPath: '/convertidos/'
      preLoaderRoute: typeof AuthConvertidosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/discipulado/$id': {
      id: '/_auth/discipulado/$id'
      path: '/discipulado/$id'
      fullPath: '/discipulado/$id'
      preLoaderRoute: typeof AuthDiscipuladoIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/convertidos/novo': {
      id: '/_auth/convertidos/novo'
      path: '/convertidos/novo'
      fullPath: '/convertidos/novo'
      preLoaderRoute: typeof AuthConvertidosNovoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/convertidos/$id/': {
      id: '/_auth/convertidos/$id/'
      path: '/convertidos/$id'
      fullPath: '/convertidos/$id/'
      preLoaderRoute: typeof AuthConvertidosIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/convertidos/$id/jornada': {
      id: '/_auth/convertidos/$id/jornada'
      path: '/convertidos/$id/jornada'
      fullPath: '/convertidos/$id/jornada'
      preLoaderRoute: typeof AuthConvertidosIdJornadaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/convertidos/$id/editar': {
      id: '/_auth/convertidos/$id/editar'
      path: '/convertidos/$id/editar'
      fullPath: '/convertidos/$id/editar'
      preLoaderRoute: typeof AuthConvertidosIdEditarRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface SlugRouteChildren {
  SlugLoginRoute: typeof SlugLoginRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugLoginRoute: SlugLoginRoute,
  SlugIndexRoute: SlugIndexRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDiscipuladoresRoute: typeof AuthDiscipuladoresRoute
  AuthIgrejasRoute: typeof AuthIgrejasRoute
  AuthManualRoute: typeof AuthManualRoute
  AuthModulosRoute: typeof AuthModulosRoute
  AuthQrCadastroRoute: typeof AuthQrCadastroRoute
  AuthRelatoriosRoute: typeof AuthRelatoriosRoute
  AuthUsuariosRoute: typeof AuthUsuariosRoute
  AuthConvertidosNovoRoute: typeof AuthConvertidosNovoRoute
  AuthDiscipuladoIdRoute: typeof AuthDiscipuladoIdRoute
  AuthConvertidosIndexRoute: typeof AuthConvertidosIndexRoute
  AuthDiscipuladoIndexRoute: typeof AuthDiscipuladoIndexRoute
  AuthConvertidosIdEditarRoute: typeof AuthConvertidosIdEditarRoute
  AuthConvertidosIdJornadaRoute: typeof AuthConvertidosIdJornadaRoute
  AuthConvertidosIdIndexRoute: typeof AuthConvertidosIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDiscipuladoresRoute: AuthDiscipuladoresRoute,
  AuthIgrejasRoute: AuthIgrejasRoute,
  AuthManualRoute: AuthManualRoute,
  AuthModulosRoute: AuthModulosRoute,
  AuthQrCadastroRoute: AuthQrCadastroRoute,
  AuthRelatoriosRoute: AuthRelatoriosRoute,
  AuthUsuariosRoute: AuthUsuariosRoute,
  AuthConvertidosNovoRoute: AuthConvertidosNovoRoute,
  AuthDiscipuladoIdRoute: AuthDiscipuladoIdRoute,
  AuthConvertidosIndexRoute: AuthConvertidosIndexRoute,
  AuthDiscipuladoIndexRoute: AuthDiscipuladoIndexRoute,
  AuthConvertidosIdEditarRoute: AuthConvertidosIdEditarRoute,
  AuthConvertidosIdJornadaRoute: AuthConvertidosIdJornadaRoute,
  AuthConvertidosIdIndexRoute: AuthConvertidosIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  CadastroSlugRoute: CadastroSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
